Project Dashboard/src/objects/ProjDash_Project__c.object
<CustomObject>
    <description>ProjDash - This custom object holds all project records used for project dashboard</description>
    <fields>
        <fullName>Accomplishments__c</fullName>
        <description>Project Accomplishments</description>
        <inlineHelpText>Please enter individual Accomplishments on a separate line</inlineHelpText>
        <label>Accomplishments</label>
        <length>600</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Action_Items__c</fullName>
        <description>Project Action Items</description>
        <inlineHelpText>Please enter individual Action Items on a separate line</inlineHelpText>
        <label>Action Items</label>
        <length>600</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Blockers__c</fullName>
        <description>Project blockers</description>
        <inlineHelpText>Please enter individual Blockers on a separate line</inlineHelpText>
        <label>Blockers</label>
        <length>600</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Escalations__c</fullName>
        <label>Escalations</label>
        <length>600</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Key_Project__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Determines whether or not a Project is  &apos;Top 3&apos; Key Project</description>
        <label>Key Project</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:User.FirstName  &amp; &quot; &quot; &amp;  Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phase__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Phase 1</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Phase 2</fullName>
                </value>
                <value>
                    <fullName>Phase 3</fullName>
                </value>
                <value>
                    <fullName>Phase 4</fullName>
                </value>
                <value>
                    <fullName>Close-Out/Close</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Project Status</description>
        <inlineHelpText>Project Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>On Track</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>At Risk</fullName>
                </value>
                <value>
                    <fullName>Past Due</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project Dashboard/src/classes/ProjDash_Controller.cls
public with sharing class  ProjDash_Controller {
   
    public List<ProjDash_Project__c> ProjLst{get;set;}
    public List<ProjDash_Project__c> keyProj{get;set;}
    public List<ProjDash_Project__c> compltdProj{get;set;}
    public static Map<String, String> ProjActionMap{get; set;}
    public static List<String> ProjIDList{get; set;}
    public String actionMapJSON {get{return JSON.serialize(ProjActionMap);}}
    public String ProjIDListJSON {get{return JSON.serialize(ProjIDList);}}
    

    public ProjDash_Controller(){
        ProjActionMap = new Map<String, String>();
        ProjIDList = new List<String>();
        

        ProjLst = [
            SELECT
                ID
                ,Name
                ,Phase__c
                ,Status__c
                ,Action_Items__c
                ,Blockers__c
                ,Escalations__c
                ,Deadline__c
                ,Accomplishments__c
                ,Owner_Name__c
            FROM ProjDash_Project__c
            WHERE Status__c!='Complete'
        ];

        compltdProj = [
            SELECT
                ID
                ,Name
                ,Phase__c
                ,Status__c
                ,Action_Items__c
                ,Blockers__c
                ,Escalations__c
                ,Deadline__c
                ,Accomplishments__c
                ,Owner_Name__c
            FROM ProjDash_Project__c
            WHERE Status__c='Complete'
        ];

        keyProj = [
            SELECT
                ID
                ,Name
                ,Phase__c
                ,Status__c
                ,Action_Items__c
                ,Blockers__c
                ,Escalations__c
                ,Deadline__c
                ,Accomplishments__c
                ,Key_Project__c
                ,OwnerId
                ,Owner_Name__c
            FROM ProjDash_Project__c
            Where Key_Project__c = True
            ORDER BY LastModifiedDate desc
            LIMIT 3
        ];

        setActionCountMap(ProjLst);
    }

    public static void setActionCountMap(List<ProjDash_Project__c> proj) {
        for (ProjDash_Project__c i : proj) {
            ProjActionMap.put(i.id, String.valueOf(getActionCount(i.Action_Items__c)));
            ProjIDList.add(i.id);
        }
    }

    public static Integer getActionCount(String txt) {
		return (txt == null || txt.length() == 0) ? 0 : (txt.countMatches('<br>') + 1);
    }


}